"""empty message

Revision ID: 270b63b1fae0
Revises: 9953b304b153
Create Date: 2018-05-02 20:39:06.024566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270b63b1fae0'
down_revision = '9953b304b153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likenum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'likenum')
    # ### end Alembic commands ###
