"""empty message

Revision ID: 3798e12eef4c
Revises: 270b63b1fae0
Create Date: 2018-05-03 21:59:01.918853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3798e12eef4c'
down_revision = '270b63b1fae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_img')
    # ### end Alembic commands ###
