"""empty message

Revision ID: 8607523a74ce
Revises: 3a85011a9bfb
Create Date: 2018-01-15 15:05:11.654675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8607523a74ce'
down_revision = '3a85011a9bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_publish_date'), 'post', ['publish_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_publish_date'), table_name='post')
    # ### end Alembic commands ###
