"""empty message

Revision ID: 8e5e629a5b24
Revises: f616f2ca3a2a
Create Date: 2018-05-08 20:56:42.478188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5e629a5b24'
down_revision = 'f616f2ca3a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('weight_value', sa.Float(), nullable=True))
    op.create_index(op.f('ix_post_weight_value'), 'post', ['weight_value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_weight_value'), table_name='post')
    op.drop_column('post', 'weight_value')
    # ### end Alembic commands ###
