"""empty message

Revision ID: 9953b304b153
Revises: c1d976d1382f
Create Date: 2018-05-01 22:29:53.103944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9953b304b153'
down_revision = 'c1d976d1382f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('comment_id', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'comment_id')
    # ### end Alembic commands ###
