"""empty message

Revision ID: 997bb4de27ba
Revises: 0e430a3c08a6
Create Date: 2018-01-22 14:06:47.714149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997bb4de27ba'
down_revision = '0e430a3c08a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('comment_body', sa.String(length=255), nullable=True))
    op.add_column('message', sa.Column('comment_username', sa.String(length=255), nullable=True))
    op.add_column('message', sa.Column('post_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'post_title')
    op.drop_column('message', 'comment_username')
    op.drop_column('message', 'comment_body')
    # ### end Alembic commands ###
