"""empty message

Revision ID: e6bbf924ab80
Revises: 7bce4f3ac10b
Create Date: 2018-01-24 11:15:36.516174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bbf924ab80'
down_revision = '7bce4f3ac10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'tag', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'parent_id')
    # ### end Alembic commands ###
